# Generated by Django 2.2.19 on 2022-12-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_recipe_ingredientrecipe_tagrecipe_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Recipe_name'),
        ),
    ]
