# Generated by Django 2.2.19 on 2022-12-25 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_created_cart_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-id',), 'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
    ]
