# Generated by Django 2.2.19 on 2022-12-26 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_add_ordering_in_recipe_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Количество должно быть не менее 1')], verbose_name='Amount'),
        ),
    ]
